### ISSUE TITLE
Apache Tomcat looks vulnerable too.

### ISSUE THREAD

**Issue by AlienKnalKoe** [NCSC-NL/log4shell#233]
Found CVE-2021-44228 vulnerability in \tomcat\webapps\ROOT\WEB-INF\lib\log4j-core-2.13.2.jar, log4j 2.13.2

**Comment by 9jx5PkHvr** [comment]
Dear AlienKnalKoe, thank you for your contribution. Apache themselves refer to Tomcat as "Not vulnerable". We would like to stick to that message until they publish otherwise. Please see the following link: https://mail-archives.apache.org/mod_mbox/www-announce/202112.mbox/%3c028d1058-2e48-f72c-2037-2070d73b7411@apache.org%3e. It might be that your findings are in a configuration as described by the Tomcat security team.
